services:
  cell-allocator:
    build: .
    container_name: cell-allocator
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
